### ISSUE TITLE
Feature : add animation to the splash screen 

### ISSUE THREAD

**Issue by Swarnima2004** [Garvitjoshi1/Invisi_Studio#1]
Description : add an animation in the splash screen to make better user experience and appealing.

**Comment by Swarnima2004** [comment]
i would like to work on this.

**Comment by Garvitjoshi1** [comment]
Are you wworking upon it ?

**Comment by Swarnima2004** [comment]
yes

**Comment by Garvitjoshi1** [comment]
Nope, it was a project given to us in semester test.
